syntax = "proto3";

package board.v1;

option go_package = "github.com/Kredo15/task-board/protos/gen/go/board/v1";

import "board.proto";


message CreateBoardRequest {
  string title = 1;
  string description = 2;
}

message CreateBoardResponse {
  Board board = 1;
}

message ListBoardsRequest {}

message ListBoardsResponse {
  repeated Board boards = 1;
}

message GetBoardRequest {
  string board_id = 1;
}

message GetBoardResponse {
  BoardView view = 1;
}

message UpdateBoardRequest {
  string board_id = 1;
  string title = 2;
  string description = 3;
}

message UpdateBoardResponse {
    Board board = 1;
}

message DeleteBoardRequest {
  string board_id = 1;
}

message DeleteBoardResponse {}

message CreateColumnRequest {
  string board_id = 1;
  string title = 2;
}

message CreateColumnResponse {
  Column column = 1;
}

message UpdateColumnRequest {
  string column_id = 1;
  string title = 2;
}

message UpdateColumnResponse {
    Column column = 1;
}

message MoveColumnRequest {
  string column_id = 1;
  optional string after_column_id = 3;
  optional string before_column_id = 4;
}

message MoveColumnResponse {
  Column column = 1;
}

message DeleteColumnRequest {
  string column_id = 1;
}

message DeleteColumnResponse {}

message CreateTaskRequest {
  string column_id = 1;
  string title = 2;
  string description = 3;
  string assignee_id = 4;
}

message CreateTaskResponse {
  Task task = 1;
}

message UpdateTaskRequest {
  string task_id = 1;
  string title = 2;
  string description = 3;
  string assignee_id = 4;
}

message UpdateTaskResponse {
  Task task = 1;
}

message MoveTaskRequest {
  string task_id = 1;
  string to_column_id = 2;
  optional string after_task_id = 3;
  optional string before_task_id = 4;
}

message MoveTaskResponse {
  Task task = 1;
}

message DeleteTaskRequest {
  string task_id = 1;
}

message DeleteTaskResponse {}
// BoardService определяет службу gRPC для управления досками, колонками и задачами.
service BoardService {
    // Методы для управления досками
    // Метод для создания доски
    rpc CreateBoard(CreateBoardRequest) returns (CreateBoardResponse);
    // Метод для получения списка досок
    rpc ListBoards(ListBoardsRequest) returns (ListBoardsResponse);
    // Метод для получения доски с колонками и задачами по ID
    rpc GetBoard(GetBoardRequest) returns (GetBoardResponse);
    // Метод для обновления доски
    rpc UpdateBoard(UpdateBoardRequest) returns (UpdateBoardResponse);
    // Метод для удаления доски
    rpc DeleteBoard(DeleteBoardRequest) returns (DeleteBoardResponse);

    // Методы для управления колонками
    // Метод для создания колонки
    rpc CreateColumn(CreateColumnRequest) returns (CreateColumnResponse);
    // Метод для обновления колонки
    rpc UpdateColumn(UpdateColumnRequest) returns (UpdateColumnResponse);
    // Метод для перемещения колонки
    rpc MoveColumn(MoveColumnRequest) returns (MoveColumnResponse);
    // Метод для удаления колонки
    rpc DeleteColumn(DeleteColumnRequest) returns (DeleteColumnResponse);

    // Методы для управления задачами
    // Метод для создания задачи
    rpc CreateTask(CreateTaskRequest) returns (CreateTaskResponse);
    // Метод для обновления задачи
    rpc UpdateTask(UpdateTaskRequest) returns (UpdateTaskResponse);
    // Метод для перемещения задачи
    rpc MoveTask(MoveTaskRequest) returns (MoveTaskResponse);
    // Метод для удаления задачи
    rpc DeleteTask(DeleteTaskRequest) returns (DeleteTaskResponse);
}